project:
  type: "cli"
  language:
    name: go
    version: 1.24.3

analysis:
  files_include_path: ".phengineer/.includefiles"
  files_exclude_path: ".phengineer/.ignorefiles"
  file_limits:
    max_file_size: "1MB"
    max_files: 1000