project:
    type: application
    language:
        name: go
        version: "1.24"
analysis:
    analysis_files_path: app/.phengineer/.analysisFiles
    ignore_files_path: app/.phengineer/.ignoreFiles
    file_limits:
        max_file_size: 10MB
        max_files: 1000
